ln -s emojis/1F40C.png hello_world.png
ln -s emojis/1F98B.png current_working_directory.png
ln -s emojis/1F41B.png list_files.png
ln -s emojis/1F41C.png print_file_contents.png
ln -s emojis/1F578.png last_lines.png
ln -s emojis/1F41D.png find_string_in_a_file.png
ln -s emojis/1F41E.png search_for_files_containing_string.png
ln -s emojis/1F997.png search_for_files_by_extension.png
ln -s emojis/1F577.png search_for_string_in_files_recursive.png
ln -s emojis/1F982.png extract_ip_addresses.png
ln -s emojis/1F99F.png delete_files.png
ln -s emojis/1FAB0.png count_files.png
ln -s emojis/1FAB1.png simple_sort.png
ln -s emojis/1F9A0.png count_string_in_line.png
ln -s emojis/1F435.png split_on_a_char.png
ln -s emojis/1F436.png print_number_sequence.png
ln -s emojis/1F43A.png remove_files_with_extension.png
ln -s emojis/1F98A.png replace_text_in_files.png
ln -s emojis/1F431.png sum_all_numbers.png
ln -s emojis/1F981.png just_the_files.png
ln -s emojis/1F42F.png remove_extensions_from_files.png
ln -s emojis/1F434.png replace_spaces_in_filenames.png
ln -s emojis/1F984.png dirs_containing_files_with_extension.png
ln -s emojis/1F42E.png files_starting_with_a_number.png
ln -s emojis/1F437.png print_nth_line.png
ln -s emojis/1F42D.png reverse_readme.png
ln -s emojis/1F439.png remove_duplicate_lines.png
ln -s emojis/1F430.png disp_table.png
ln -s emojis/1F43B.png find_primes.png
ln -s emojis/1F43C.png print_common_lines.png
ln -s emojis/1F423.png print_line_before.png
ln -s emojis/1F99A.png print_files_if_different.png
ln -s emojis/1F438.png nested_dirs.png
ln -s emojis/1F432.png find_tabs_in_a_file.png
ln -s emojis/1F338.png remove_files_without_extension.png
ln -s emojis/1F339.png remove_files_with_a_dash.png
ln -s emojis/1F33A.png print_sorted_by_key.png
ln -s emojis/1F33B.png IPv4_listening_ports.png
