#!/bin/bash

if ! [[ $(find . -type f | wc -l) == 4 ]]; then
	echo "Test failed, expecting 4 files."
	fail=1
fi

if ! [[ $(find . -name "*.txt" | wc -l) == 3 ]]; then
	echo "Test failed, expecting 3 files with a .txt extension."
	fail=1
fi

if ! [[ $(find . -name "*.exe" | wc -l) == 1 ]]; then
	echo "Test failed, expecting 1 files with a .exe extension."
	fail=1
fi

[[ -n "$fail" ]] && exit 1
exit 0
