#!/bin/bash

if ! [[ $(find . -type f | wc -l) == 2 ]]; then
    echo "Test failed, expecting 2 files."
    fail=1
fi

if ! [[ $(find . -name "-*" | wc -l) == 0 ]]; then
    echo "Test failed, files with dashes exist."
    fail=1
fi

[[ -n "$fail" ]] && exit 1
exit 0
