#!/bin/bash

if ! [[ $(find . -type f -name "*.*") == "" ]]; then
    echo "Test failed, there are still files with extensions in the current directory."
    fail=1
fi

if ! [[ $(find . -type f | wc -l) == 9 ]]; then
    echo "Test failed, expecting 9 files."
    fail=1
fi

[[ -n "$fail" ]] && exit 1
exit 0
